### ISSUE TITLE
Revisión documentación Subsistema de Presupuesto

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente_V2#4]
Revisión de documentos de análisis

**Comment by mcrubianot** [comment]
Se revisan los siguientes documentos:
https://docs.google.com/document/d/1DHKWStkSUNSBZbmq6lSGKDDfh--YWSs708mqMDnPyO4/edit
https://docs.google.com/document/d/1g7N8j0qxoGTHJdqtEM3BvghQmd8qBU-rf-IMqOeuDRw/edit#heading=h.et2c7gsyofrx
https://docs.google.com/document/d/1uxxF4FsvTOtO04ipDSfe4QjIjqdfBsxOAFkNufteIeI/edit
https://docs.google.com/document/d/1N5CK5sNeIBAvx9VV8k8NE9VHwcBegIJ0Pbu4QH8dkRQ/edit
https://docs.google.com/document/d/1XSlydi7cBJyV-Xd47QCCPDjKJMbsE-1Z60qgQLLmiJ4/edit#
https://docs.google.com/document/d/1myI1aS-6GXuJTvDVzM70FdqJK6anUR8hlVPQeFXEb94/edit?usp=sharing
https://docs.google.com/document/d/1Y289yA4MP_MuUr4LafixsrFKwnBZQEe90XgTuAKr3j8/edit

**Comment by mcrubianot** [comment]
Se pausa esta revisión toda vez que en reunión semanal realizada el día 10 de mayo se estableció que nos informarían cuales son los parametros para cada documentos.

**Comment by mcrubianot** [comment]
No se continua con la tarea teniendo en cuenta que ya se definió que de mi parte la información que se debe entregar son:
Procedimientos o flujogramas
Historias de usuario
Actas de reuniones

**Comment by Soulfilip-UD** [comment]
El procedimiento fue documentado, y lo referente al seguimiento fue finalizado. Se cierra el Issue
