### ISSUE TITLE
Reunión con la Oficina Asesora de Planeación para validar procedimiento de Fuentes de Financiamiento

### ISSUE THREAD

**Issue by mcrubianot** [udistrital/financiera_cliente_V2#7]

**Comment by mcrubianot** [comment]
Se realiza la respectiva reunión el día 29/05/2019 se levanta la respectiva acta para aprobación

Acta No.4 - Fuentes de Financiamiento - Kronos

https://docs.google.com/document/d/1m_glDxafLNmPOUaYDQkDQxsUUyBPViHEEuPGQWFGMpY/edit

**Comment by mcrubianot** [comment]
Se envia el siguiente correo y se queda a la espera de la aprobación de la respectiva acta

de: | Oficina Asesora de Sistemas Universidad Distrital<computo@udistrital.edu.co>
-- | --
para: | Oficina Asesora de Planeación y Control Universidad Distrital <planeac@udistrital.edu.co>
Cc: | sgarzong@correo.udistrital.edu.co,Santiago Duran Mora <sduranm@correo.udistrital.edu.co>,mapolancol@udistrital.edu.co
Cco: | mcrubianot@udistrital.edu.co
fecha: | 12 jun. 2019 9:54
asunto: | Acta Revisión procedimiento - Fuentes de Financiamiento

**Comment by DianaPatriciaRamirez** [comment]
También se levantaron las siguientes actas con respecto a Fuentes de Financiamiento

Acta No.7 - Kronos: https://docs.google.com/document/d/1okF_kc_gJlVozaXR3v2ZuV3GiFR6bpH_IcB9vX-anA8/edit

Acta No.14 - Kronos: https://docs.google.com/document/d/1A7balExQqTNBIEeaSCfsGYQwc1mY81WzdZ7EoF-8wGU/edit

Acta No.22 - Kronos: https://docs.google.com/document/d/1m_glDxafLNmPOUaYDQkDQxsUUyBPViHEEuPGQWFGMpY/edit
